SELECT 'CREATE DATABASE SPRC'
WHERE NOT EXISTS 
(SELECT FROM pg_database WHERE datname = 'SPRC');

CREATE TABLE IF NOT EXISTS Tari (
	id SERIAL NOT NULL PRIMARY KEY,
	nume VARCHAR(50) UNIQUE,
	lat FLOAT(3) NOT NULL,
	lon FLOAT(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS Orase (
	id SERIAL NOT NULL PRIMARY KEY,
	idTara INT,
	nume VARCHAR(50),
	lat FLOAT(3) NOT NULL,
	lon FLOAT(3) NOT NULL,
	CONSTRAINT fk_tara FOREIGN KEY (idTara)
	REFERENCES Tari (id) ON DELETE CASCADE,
	UNIQUE (idTara, nume)
);

CREATE TABLE IF NOT EXISTS Temperaturi (
	id SERIAL NOT NULL PRIMARY KEY,
	valoare FLOAT(3) NOT NULL,
	timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	idOras INT,
	CONSTRAINT fk_oras FOREIGN KEY (idOras)
	REFERENCES Orase (id) ON DELETE CASCADE,
	UNIQUE (idOras, timestamp)
);
